### ISSUE TITLE
could you successfully download the entire voxceleb1 dataset？

### ISSUE THREAD

**Issue by cjeen** [supermusan/download_voxceleb_for_reenactment#1]
is there any broken link of youtube videos？how do you handle these videos?

**Comment by supermusan** [comment]
> is there any broken link of youtube videos？how do you handle these videos?

Some videos were taken down from YouTube. I could not download them either.

**Comment by cjeen** [comment]
> > is there any broken link of youtube videos？how do you handle these videos?
> 
> Some videos were taken down from YouTube. I could not download them either.

thanks! and would you mind contacting  with me?I met some problems with downloading the voxceleb1, I sincerely hope to talk with you about these problems.My qq:860360956 or my wechat:senbein_py.Thanks a lot!

**Comment by supermusan** [comment]
> > > is there any broken link of youtube videos？how do you handle these videos?
> > 
> > 
> > Some videos were taken down from YouTube. I could not download them either.
> 
> thanks! and would you mind contacting with me?I met some problems with downloading the voxceleb1, I sincerely hope to talk with you about these problems.My qq:860360956 or my wechat:senbein_py.Thanks a lot!

sorry, I prefer to use email. [weisen@ruc.edu.cn]
